package eu.wohlben.qits.githost.api;

import static io.restassured.RestAssured.given;

import eu.wohlben.qits.githost.contracts.GoldenFiles;
import io.quarkus.test.junit.QuarkusTest;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Pins {@code docs/openapi.yml} to the surface this build serves at {@code /githost/q/openapi}, the
 * way qits-projects-service pins its own. Consumers generate their clients from the committed file,
 * so an API change shows up as a reviewable diff.
 *
 * <p>It compares by default and fails with a unified diff when the served document moved; {@code
 * -Dgolden.update=true} (or {@code QITS_GOLDEN_UPDATE=true}) rewrites the file. {@code
 * info.version} is the release version and is left out of the comparison, so a release alone never
 * fails it.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  /** The one two-space-indented {@code version:} key in the document is {@code info.version}. */
  private static final Pattern INFO_VERSION = Pattern.compile("(?m)^  version: .*$");

  @Test
  public void exportOpenApiSchema() {
    String schema =
        given().when().get("/githost/q/openapi").then().statusCode(200).extract().asString();

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service -am test -Dtest=OpenApiSchemaExportTest"
            + " -Dsurefire.failIfNoSpecifiedTests=false -Dgolden.update=true` to regenerate.\n";

    GoldenFiles.compareOrWrite(
        GoldenFiles.repositoryRoot().resolve("docs").resolve("openapi.yml"),
        header + schema,
        text -> INFO_VERSION.matcher(text).replaceAll("  version: <release version>"));
  }
}
